image: contentwisetv/maven-aws-docker-gosu

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - git clone https://RepoCleaner:${BB_READ_TOKEN}@bitbucket.org/repocleaner/maven-common.git
          - mv maven-common/*.sh maven-common/settings.xml -t .
          - chmod +x deploy-lambda.sh
          - ./deploy-lambda.sh "twitter-bot"
