image: maven:3.3.9

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - git clone https://RepoCleaner:${BB_READ_TOKEN}@bitbucket.org/repocleaner/maven-common.git
          - mvn -B -s maven-common/settings.xml clean deploy -Dusername="$S3_ACCESS_KEY" -Dpassword="$S3_SECRET_ACCESS_KEY"
